version: '3.8'

services:
  db:
    build: ./ddbb
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: defaultdb_uk1q_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Tenemos que exponer el puerto para podder ver la bbdd desde un cliente

  backend:
    build: ./backend/area_backend  # <--- Apunta a la carpeta donde moviste el Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/area_backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://defaultdb_uk1q_user:password@db:5432/defaultdb
    depends_on:
      - db

  frontend:
    build: ./frontend
    #command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "4200:80"
    stdin_open: true # Necesario para que funcione el CLI de Angular
    tty: true

volumes:
  postgres_data:
