services:

  backend:

    ports:
      - "${BACK_PORT}:8000"

    environment:
      FLASK_DEBUG: "0"
      FLASK_ENV: production


  frontend:   
    build:
      context: ./frontend
      target: production

    depends_on:
          backend:
            condition: service_healthy

    volumes: []

    ports:
      - "8443:443"

    environment:
      URL_BACK: /

    entrypoint:
      - /docker-entrypoint.sh

    command: []