services:
  backend:
    # En producción quitamos los volumes locales para usar el código estático de la imagen
    volumes: []
    command: gunicorn app:app --bind 0.0.0.0:8000 # O el comando de prod que uses

  frontend:
    build:
      context: ./frontend
      target: production # Obliga a usar la capa de Nginx optimizada
    volumes: []
    ports:
      - "${FRONT_PORT}:80" # El puerto elegido saldrá por el 80 de Nginx
    command: [] # Resetea el comando de desarrollo para usar el ENTRYPOINT del Dockerfile